name: Lint

on:
  push:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  super-linter:
    name: Super Linter
    uses: harryzcy/github-actions/.github/workflows/linter.yml@25d834bc6f100ee46b88756cb6ec46204f04705a # main

  prettier:
    name: Prettier
    uses: harryzcy/github-actions/.github/workflows/prettier.yml@25d834bc6f100ee46b88756cb6ec46204f04705a # main
  
  eslint:
    name: ESLint
    uses: harryzcy/github-actions/.github/workflows/npm-lint.yml@25d834bc6f100ee46b88756cb6ec46204f04705a # main

  spelling:
    name: Spelling
    uses: harryzcy/github-actions/.github/workflows/spelling.yml@25d834bc6f100ee46b88756cb6ec46204f04705a # main

  project-yaml:
    name: Project YAML Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24

      - name: Check project yaml
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            const { default: script } = await import('${{ github.workspace }}/script/check_project_yaml.js')
            script()

  project-date:
    name: Project Date Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install yaml

      - name: Check project date
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            const { default: script } = await import('${{ github.workspace }}/script/check_project_date.js')
            script({ github })
