name: Lint

on:
  push:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  super-linter:
    name: Super Linter
    uses: harryzcy/github-actions/.github/workflows/linter.yml@a0dee436184d6eeacdc042b8487c78eb3186e1cd # main

  prettier:
    name: Prettier
    uses: harryzcy/github-actions/.github/workflows/prettier.yml@a0dee436184d6eeacdc042b8487c78eb3186e1cd # main
  
  eslint:
    name: ESLint
    uses: harryzcy/github-actions/.github/workflows/npm-lint.yml@a0dee436184d6eeacdc042b8487c78eb3186e1cd # main

  spelling:
    name: Spelling
    uses: harryzcy/github-actions/.github/workflows/spelling.yml@a0dee436184d6eeacdc042b8487c78eb3186e1cd # main

  project-yaml:
    name: Project YAML Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24

      - name: Check project yaml
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            const { default: script } = await import('${{ github.workspace }}/script/check_project_yaml.js')
            script()

  project-date:
    name: Project Date Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install yaml

      - name: Check project date
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            const { default: script } = await import('${{ github.workspace }}/script/check_project_date.js')
            script({ github })
